# Generated by Django 2.1.4 on 2019-06-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_auto_20190602_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artcontent',
            options={'ordering': ['chapter_add_date']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='art_owner',
            new_name='user_owner',
        ),
    ]
