# Generated by Django 2.1.4 on 2019-06-21 21:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_auto_20190609_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcontent',
            name='chapter_content',
            field=tinymce.models.HTMLField(verbose_name='文章内容'),
        ),
    ]
