# Generated by Django 2.2.1 on 2019-06-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_auto_20190621_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcontent',
            name='chapter_add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artdiscuss',
            name='discuss_add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
